name: hidden_drawer_menu
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true  

  assets:
    - assets/dark_grunge_bk.jpg
    - assets/wood_bk.jpg
    - assets/eggs_in_skillet.jpg
    - assets/steak_on_cooktop.jpg
    - assets/spoons_of_spices.jpg
    - assets/other_screen_bk.jpg
    - assets/other_screen_card_photo.jpg
    
  fonts:
     - family: mermaid
       fonts:
         - asset: assets/Mermaid1001.ttf
     - family: bebas-neue
       fonts:
         - asset: assets/BebasNeue-Regular.ttf
